import { MigrationInterface, QueryRunner } from 'typeorm';

/**
 * Support Tickets feature (initial schema).
 *
 *   - tickets         : one row per ticket, identified by `ticket_number`
 *                       generated from the `ticket_number_seq` sequence.
 *   - ticket_messages : reply thread. The first row mirrors the original
 *                       ticket content so the conversation is self-contained.
 *
 * NOTE: This is the original migration shipped with the feature. A follow-up
 * migration (`1780300000001-FixSupportTicketsSnapshotAndDeleteBehavior`)
 * adds the snapshot fields, activity tracking, and switches the creator FK
 * to `ON DELETE SET NULL`. Do not edit this file in place once it has been
 * applied anywhere shared — fix forward via the follow-up migration.
 */
export class AddSupportTickets1780300000000 implements MigrationInterface {
  name = 'AddSupportTickets1780300000000';

  public async up(qr: QueryRunner): Promise<void> {
    // ── Enums ─────────────────────────────────────────────────────────────
    await qr.query(`
      DO $$ BEGIN
        CREATE TYPE "public"."tickets_type_enum" AS ENUM (
          'PAYMENT','CREDITS','TECHNICAL_ISSUE','ACCOUNT','BILLING',
          'FEATURE_REQUEST','ENTERPRISE_SUPPORT','GENERAL'
        );
      EXCEPTION WHEN duplicate_object THEN NULL; END $$;
    `);
    await qr.query(`
      DO $$ BEGIN
        CREATE TYPE "public"."tickets_status_enum" AS ENUM (
          'OPEN','IN_PROGRESS','WAITING_FOR_USER','WAITING_FOR_ADMIN','RESOLVED','CLOSED'
        );
      EXCEPTION WHEN duplicate_object THEN NULL; END $$;
    `);
    await qr.query(`
      DO $$ BEGIN
        CREATE TYPE "public"."tickets_priority_enum" AS ENUM (
          'LOW','MEDIUM','HIGH','URGENT'
        );
      EXCEPTION WHEN duplicate_object THEN NULL; END $$;
    `);
    await qr.query(`
      DO $$ BEGIN
        CREATE TYPE "public"."tickets_user_role_enum" AS ENUM (
          'USER','ENTERPRISE_USER','ENTERPRISE_ADMIN'
        );
      EXCEPTION WHEN duplicate_object THEN NULL; END $$;
    `);
    await qr.query(`
      DO $$ BEGIN
        CREATE TYPE "public"."ticket_messages_sender_role_enum" AS ENUM (
          'USER','ENTERPRISE_USER','ENTERPRISE_ADMIN','SUPER_ADMIN','ADMIN'
        );
      EXCEPTION WHEN duplicate_object THEN NULL; END $$;
    `);

    // ── Sequence backing ticket_number (atomic across concurrent transactions) ──
    await qr.query(
      `CREATE SEQUENCE IF NOT EXISTS ticket_number_seq START 1 INCREMENT 1`,
    );

    // ── tickets table (original shape) ───────────────────────────────────
    await qr.query(`
      CREATE TABLE IF NOT EXISTS tickets (
        id                  UUID PRIMARY KEY DEFAULT gen_random_uuid(),
        ticket_number       VARCHAR(32) NOT NULL UNIQUE,
        subject             VARCHAR(150) NOT NULL,
        type                "public"."tickets_type_enum"     NOT NULL,
        content             TEXT NOT NULL,
        status              "public"."tickets_status_enum"   NOT NULL DEFAULT 'OPEN',
        priority            "public"."tickets_priority_enum" NOT NULL DEFAULT 'MEDIUM',
        created_by_user_id  UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
        user_role           "public"."tickets_user_role_enum" NOT NULL,
        enterprise_id       UUID NULL REFERENCES enterprises(id) ON DELETE SET NULL,
        assigned_admin_id   UUID NULL REFERENCES admins(id) ON DELETE SET NULL,
        last_reply_at       TIMESTAMPTZ NULL,
        resolved_at         TIMESTAMPTZ NULL,
        closed_at           TIMESTAMPTZ NULL,
        created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
        updated_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
        deleted_at          TIMESTAMPTZ NULL
      )
    `);

    await qr.query(
      `CREATE INDEX IF NOT EXISTS idx_tickets_status        ON tickets (status)`,
    );
    await qr.query(
      `CREATE INDEX IF NOT EXISTS idx_tickets_priority      ON tickets (priority)`,
    );
    await qr.query(
      `CREATE INDEX IF NOT EXISTS idx_tickets_type          ON tickets (type)`,
    );
    await qr.query(
      `CREATE INDEX IF NOT EXISTS idx_tickets_creator       ON tickets (created_by_user_id)`,
    );
    await qr.query(
      `CREATE INDEX IF NOT EXISTS idx_tickets_enterprise    ON tickets (enterprise_id)`,
    );
    await qr.query(
      `CREATE INDEX IF NOT EXISTS idx_tickets_created_at    ON tickets (created_at)`,
    );
    await qr.query(
      `CREATE INDEX IF NOT EXISTS idx_tickets_not_deleted   ON tickets (deleted_at) WHERE deleted_at IS NULL`,
    );

    // ── ticket_messages table ───────────────────────────────────────────
    // sender_id is intentionally NOT a FK because it can reference either
    // users(id) or admins(id) — sender_role tells the application which.
    await qr.query(`
      CREATE TABLE IF NOT EXISTS ticket_messages (
        id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
        ticket_id     UUID NOT NULL REFERENCES tickets(id) ON DELETE CASCADE,
        sender_id     UUID NOT NULL,
        sender_role   "public"."ticket_messages_sender_role_enum" NOT NULL,
        message       TEXT NOT NULL,
        created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
        updated_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
        deleted_at    TIMESTAMPTZ NULL
      )
    `);
    await qr.query(
      `CREATE INDEX IF NOT EXISTS idx_tkt_msg_ticket ON ticket_messages (ticket_id, created_at)`,
    );
    await qr.query(
      `CREATE INDEX IF NOT EXISTS idx_tkt_msg_sender ON ticket_messages (sender_id)`,
    );
  }

  public async down(qr: QueryRunner): Promise<void> {
    await qr.query(`DROP INDEX IF EXISTS idx_tkt_msg_ticket`);
    await qr.query(`DROP INDEX IF EXISTS idx_tkt_msg_sender`);
    await qr.query(`DROP TABLE IF EXISTS ticket_messages`);

    await qr.query(`DROP INDEX IF EXISTS idx_tickets_status`);
    await qr.query(`DROP INDEX IF EXISTS idx_tickets_priority`);
    await qr.query(`DROP INDEX IF EXISTS idx_tickets_type`);
    await qr.query(`DROP INDEX IF EXISTS idx_tickets_creator`);
    await qr.query(`DROP INDEX IF EXISTS idx_tickets_enterprise`);
    await qr.query(`DROP INDEX IF EXISTS idx_tickets_created_at`);
    await qr.query(`DROP INDEX IF EXISTS idx_tickets_not_deleted`);
    await qr.query(`DROP TABLE IF EXISTS tickets`);

    await qr.query(`DROP SEQUENCE IF EXISTS ticket_number_seq`);

    await qr.query(
      `DROP TYPE IF EXISTS "public"."ticket_messages_sender_role_enum"`,
    );
    await qr.query(`DROP TYPE IF EXISTS "public"."tickets_user_role_enum"`);
    await qr.query(`DROP TYPE IF EXISTS "public"."tickets_priority_enum"`);
    await qr.query(`DROP TYPE IF EXISTS "public"."tickets_status_enum"`);
    await qr.query(`DROP TYPE IF EXISTS "public"."tickets_type_enum"`);
  }
}
